Util classes for building and validating schema json
grookage/leia pull request #11
Opened 2024-11-28 07:00 UTC by abhigun

- LeiaClient - SchemaUtil to add support for building SchemaAttributes from the Schema class
- LeiaCore - Added API support to validate schema payload against the SchemaDetails of a specified key

2024-11-29 06:50 UTC, koushikr commented on leia-client/src/main/java/com/grookage/leia/client/utils/SchemaUtil.java
> +public class SchemaUtil {
Not quite SchemaUtil, no? Actually SchemaAttributeUtils?

2024-11-29 06:50 UTC, koushikr commented on leia-client/src/main/java/com/grookage/leia/client/utils/SchemaUtil.java
> +        return getAllFields(klass)
You can create a FieldUtils in the models, and move getAllFields there, instead of duplicating it here

2024-11-29 06:51 UTC, koushikr commented on leia-client/src/main/java/com/grookage/leia/client/utils/SchemaUtil.java
> +    private List<Field> getAllFields(Class<?> type) {
Refer to the above, move this out to FieldUtils

2024-11-29 06:51 UTC, koushikr commented on leia-client/src/main/java/com/grookage/leia/client/utils/SchemaUtil.java
> +        Set<QualifierInfo> qualifierInfos = new HashSet<>();
var

2024-11-29 06:52 UTC, koushikr commented on leia-client/src/main/java/com/grookage/leia/client/utils/SchemaUtil.java
> +        if (field.isAnnotationPresent(Standard.class)) {
Don't need a Standard annotation, default is Standard

2024-11-29 06:54 UTC, koushikr commented on leia-core/src/main/java/com/grookage/leia/core/utils/ValidationUtils.java
> +public class ValidationUtils {
Shouldn't be here, there's a leia-schema-validator, it should be there

2024-11-29 06:59 UTC, koushikr commented on leia-models/src/main/java/com/grookage/leia/models/annotations/qualifiers/ShortLived.java
> +    int ttlSeconds();
This is long I think?

2024-11-29 07:01 UTC, koushikr commented on leia-schema-validator/src/main/java/com/grookage/leia/validator/utils/SchemaValidationUtils.java
> +                          SchemaAttribute attribute, final ParameterizedType parameterizedType) {
SchemaAttribute in args is not final?

2024-11-29 07:01 UTC, koushikr commented on leia-schema-validator/src/main/java/com/grookage/leia/validator/utils/SchemaValidationUtils.java
>          Type[] typeArguments = parameterizedType.getActualTypeArguments();
var

2024-11-29 07:08 UTC, koushikr requested changes
Added a few comments. A couple of high level questions, should we change the SchemaValidatable annotation to look like the following?

`@Target({ElementType.TYPE})
@Retention(RetentionPolicy.RUNTIME)
public @interface SchemaDefinition {

    SchemaType type() default SchemaType.JSON;

    SchemaValidationType validationType() default SchemaValidationType.MATCHING;

    SchemaState state() default SchemaState.CREATED;

    String schemaName();

    String versionId();

    String namespace();

    String description() default "";

    Class<?>[] transformationTargets();
}`

And use the above to build the CreateSchemaRequest itself?

Roughly I'm thinking, 

`@Override
    public Optional<CreateSchemaRequest> getDetails(Class<?> klass) {
        if (null == klass) {
            log.debug("No klass definition provided. Can't convert");
            return Optional.empty();
        }
        final var schemaDefinition = klass.getAnnotation(SchemaDefinition.class);
        if (null == schemaDefinition) {
            log.debug("The klass {} is not annotated with SchemaDefinition. Can't convert", klass.getSimpleName());
            return Optional.empty();
        }
        return Optional.of(CreateSchemaRequest.builder()
                .schemaType(schemaDefinition.type())
                .validationType(schemaDefinition.validationType())
                .description(schemaDefinition.description())
                .schemaName(schemaDefinition.schemaName())
                .namespace(schemaDefinition.namespace())
                .attributes(
                        FieldUtils.getAllFields(klass)
                                .stream()
                                .map(SchemaAttributeUtils::getAttribute)
                                .collect(Collectors.toSet())
                )
                .transformationTargets(
                        SchemaAttributeUtils.getTransformationTargets(
                                klass,
                                schemaDefinition.transformationTargets()
                        )
                )
                .build());
    }`


Also should we do SchemaUtils (Or SchemaAttributeUtils) as part of the schema-validator itself - also the ValidationUtils must move here? leia-client can use the validator as a dependency then?

2024-12-01 10:23 UTC, abhigun commented on leia-client/src/main/java/com/grookage/leia/client/utils/SchemaUtil.java
> +public class SchemaUtil {
Done. Moved SchemaAttribute related classes to separate utils class

2024-12-01 10:24 UTC, abhigun commented on leia-client/src/main/java/com/grookage/leia/client/utils/SchemaUtil.java
> +        return getAllFields(klass)
Done. Created a `Utils.class` to hold all the common util methods

2024-12-01 10:24 UTC, abhigun commented on leia-client/src/main/java/com/grookage/leia/client/utils/SchemaUtil.java
> +        Class<?> rawType = (Class<?>) parameterizedType.getRawType();
done

2024-12-01 10:24 UTC, abhigun commented on leia-client/src/main/java/com/grookage/leia/client/utils/SchemaUtil.java
> +    private List<Field> getAllFields(Class<?> type) {
Done

2024-12-01 10:25 UTC, abhigun commented on leia-client/src/main/java/com/grookage/leia/client/utils/SchemaUtil.java
> +        if (field.isAnnotationPresent(Standard.class)) {
Done

2024-12-01 10:25 UTC, abhigun commented on leia-client/src/main/java/com/grookage/leia/client/utils/SchemaUtil.java
> +        Set<QualifierInfo> qualifierInfos = new HashSet<>();
Done. Changed all the occurences to qualifiers

2024-12-01 10:26 UTC, abhigun commented on leia-core/src/main/java/com/grookage/leia/core/utils/ValidationUtils.java
> +public class ValidationUtils {
Moved this to leia-common module

2024-12-01 10:26 UTC, abhigun commented on leia-models/src/main/java/com/grookage/leia/models/annotations/qualifiers/ShortLived.java
> +    int ttlSeconds();
Done

2024-12-02 06:16 UTC, koushikr commented on leia-common/src/main/java/com/grookage/leia/common/utils/QualifierUtils.java
> +    public Set<QualifierInfo> getQualifierInfo(final Field field) {
Rename this to getQualifiers

2024-12-02 06:16 UTC, koushikr commented on leia-common/src/main/java/com/grookage/leia/common/utils/QualifierUtils.java
> +    public Set<QualifierInfo> getQualifierInfo(final Type type) {
Same, rename this to getQualifer

2024-12-02 06:16 UTC, koushikr commented on leia-common/src/main/java/com/grookage/leia/common/utils/QualifierUtils.java
> +    public Set<QualifierInfo> getQualifierInfo(final Class<?> klass) {
Since it is plural, I would rather call this getQualifiers(final Class<?> klass)

2024-12-02 06:18 UTC, koushikr commented on leia-common/src/main/java/com/grookage/leia/common/utils/SchemaAttributeUtils.java
> +public class SchemaAttributeUtils {
Do we need different utils, can SchemaBuilder not contain these methods as well?

2024-12-02 06:20 UTC, koushikr commented on leia-common/src/main/java/com/grookage/leia/common/utils/Utils.java
> +public class Utils {
Nothing should be called Utils.These are FieldUtils, please rename accordingly. Utils is confusing

2024-12-02 06:21 UTC, koushikr commented on leia-common/src/test/java/com/grookage/leia/common/TestUtils.java
> +public class TestUtils {
Rename this to LeiaTestUtils

2024-12-02 06:23 UTC, koushikr requested changes
Added a few comments

2024-12-02 07:38 UTC, abhigun commented on leia-common/src/test/java/com/grookage/leia/common/TestUtils.java
> +public class TestUtils {
Done

2024-12-02 07:39 UTC, abhigun commented on leia-common/src/main/java/com/grookage/leia/common/utils/Utils.java
> +public class Utils {
Renamed to FieldUtils and moved other non-related methods to respective classes

2024-12-02 07:39 UTC, abhigun commented on leia-common/src/main/java/com/grookage/leia/common/utils/SchemaAttributeUtils.java
> +public class SchemaAttributeUtils {
Moved these to SchemaBuilder class

2024-12-02 07:40 UTC, abhigun commented on leia-common/src/main/java/com/grookage/leia/common/utils/QualifierUtils.java
> +    public Set<QualifierInfo> getQualifierInfo(final Class<?> klass) {
Done, changed it `getQualifiers`

2024-12-02 07:40 UTC, abhigun commented on leia-common/src/main/java/com/grookage/leia/common/utils/QualifierUtils.java
> +    public Set<QualifierInfo> getQualifierInfo(final Type type) {
Done, changed it to `getQualifiers`

2024-12-02 07:40 UTC, abhigun commented on leia-common/src/main/java/com/grookage/leia/common/utils/QualifierUtils.java
> +    public Set<QualifierInfo> getQualifierInfo(final Field field) {
Done, changed it to `getQualifiers`

2024-12-03 07:32 UTC, merged